version: "3.8"
services:
  proxy:
    # platform: linux/x86_64
    build:
      context: ./proxy
    container_name: ${PROJECT_NAME}-proxy
    ports:
      - ${PROXY_PUBLIC_PORT}:80
      - ${PROXY_SSL_PORT}:443
    depends_on:
      - app
      - db
    volumes:
      - ./proxy/${PROXY_TEMPLATE_NAME}:/etc/nginx/conf.d/default.conf.template
      - ./proxy/log/:/var/log/nginx/
      - ${VOLUME_PATH}/:/var/www/html
      - ./proxy/ssl/:/etc/nginx/ssl/
    # コンテナ内の/etc/hostsのIPとホスト名を紐づけたい場合はアンコメントアウト
    extra_hosts:
      - "${HOSTNAME}:${HOST_IP}"
    environment:
      APP_NAME: ${PROJECT_NAME}
      PROJECT_NAME: ${PROJECT_NAME}
      PROXY_SSL_PORT: ${PROXY_SSL_PORT}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT} 
    # 環境変数を渡す
    command: /bin/sh -c "envsubst '$$PROJECT_NAME $$PROXY_SSL_PORT $$HOSTNAME $$WEBSOCKET_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  Phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PROJECT_NAME}-phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    depends_on:
      - db
    ports:
      - ${PHP_MYADMIN_PUBLIC_PORT}:80
  db:
    # platform: 'linux/amd64'
    container_name: ${PROJECT_NAME}-db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/log:/var/log/mysql
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    tty: true
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
  app:
    # platform: linux/x86_64
    build:
      context: ./app
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        USER: ${USER}
        PASSWORD: ${PASSWORD}
    container_name: ${PROJECT_NAME}-app
    # ports:
      # - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT}
    expose:
      - 3000
      - ${WEBSOCKET_PORT}
    depends_on:
      - db
    volumes:
      - ${VOLUME_PATH}/:/var/www/html
    tty: true
    environment:
      PASSWORD: ${PASSWORD}
    # コンテナ内の/etc/hostsのIPとホスト名を紐づけたい場合はアンコメントアウト
    extra_hosts:
      - "${HOSTNAME}:${HOST_IP}" # 環境変数を使用
